server:
  port: ${PORT:8081}

spring:
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true

  application:
    name: product-api

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      globally_quoted_identifiers: true

  datasource:
    platform: postgres
    url: "jdbc:postgresql://localhost:5434/product-db"
    username: admin
    password: 123456
    driverClassName: org.postgresql.Driver

  rabbitmq:
    host: ${RABBIT_MQ_HOST:localhost}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USER:guest}
    password: ${RABBIT_MQ_PASSWORD:guest}

app-config:
  secrets:
    api-secret: "ZGV2LWVuY29kZS1zZWNyZXQta2V5LTIwMjI="

  rabbit:
    exchange:
      product: product.topic

    routingKey:
      product-stock: product-stock-update.routingKey
      sales-confirmation: sales-confirmation.routingKey

    queue:
      product-stock: product-stock-update.queue
      sales-confirmation: sales-confirmation.queue
