server:
  port: ${PORT:8081}

spring:
  main:
    allow-circular-references: true

  application:
    name: product-api

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      globally_quoted_identifiers: true

  datasource:
    platform: postgres
    url: "jdbc:postgresql://localhost:5434/product-db"
    username: admin
    password: 123456
    driverClassName: org.postgresql.Driver
